services:
  - type: web
    name: sertraline-predictor
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x setup.sh && ./setup.sh
    startCommand: streamlit run project.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

