services:
  - type: web
    name: sertraline-predictor
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x setup.sh && ./setup.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7

